# baseURL = 'https://example.org/'
languageCode = 'en-us'
DefaultContentLanguage = "en"
title = 'Tread Softly'

[module]
  [[module.imports]]
    path = "github.com/kaiiiz/hugo-theme-monochrome"
    disable = false
